# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- UAT
- Development

pool:
  name: Self Hosted Agent

steps:
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchestrator_CICD_Prod_Americas'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AMCA_TX_CAN_Tiger_Tax_Report_REF'
    publishLocation: 'Container'